version: '3'

services:
  cypress-chrome:
    container_name: cypress-chrome
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - COMMAND=chrome:test
    volumes:
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/reports:/cypress-docker/cypress/reports

  cypress-firefox:
    container_name: cypress-firefox
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - COMMAND=firefox:test
    volumes:
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/reports:/cypress-docker/cypress/reports